"""removed chat_id from user

Revision ID: 8dda7c3dcbb8
Revises: db773c6fc421
Create Date: 2026-07-06 12:29:36.162376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dda7c3dcbb8'
down_revision: Union[str, Sequence[str], None] = 'db773c6fc421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
